# Generated by Django 2.2 on 2022-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
