# Generated by Django 2.2 on 2022-02-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
